/**
 * Comprehensive list of worldwide travel destinations
 * Organized by region for better performance
 */

export const destinations = [
  // Europe
  "London, United Kingdom",
  "Paris, France",
  "Rome, Italy",
  "Barcelona, Spain",
  "Madrid, Spain",
  "Amsterdam, Netherlands",
  "Berlin, Germany",
  "Munich, Germany",
  "Vienna, Austria",
  "Prague, Czech Republic",
  "Budapest, Hungary",
  "Athens, Greece",
  "Santorini, Greece",
  "Mykonos, Greece",
  "Venice, Italy",
  "Florence, Italy",
  "Milan, Italy",
  "Naples, Italy",
  "Lisbon, Portugal",
  "Porto, Portugal",
  "Dublin, Ireland",
  "Edinburgh, United Kingdom",
  "Copenhagen, Denmark",
  "Stockholm, Sweden",
  "Oslo, Norway",
  "Reykjavik, Iceland",
  "Helsinki, Finland",
  "Warsaw, Poland",
  "Krakow, Poland",
  "Brussels, Belgium",
  "Zurich, Switzerland",
  "Geneva, Switzerland",
  "Monte Carlo, Monaco",
  "Luxembourg City, Luxembourg",
  "Dubrovnik, Croatia",
  "Split, Croatia",
  "Belgrade, Serbia",
  "Sofia, Bulgaria",
  "Bucharest, Romania",
  "Kiev, Ukraine",
  "Tallinn, Estonia",
  "Riga, Latvia",
  "Vilnius, Lithuania",

  // Asia
  "Tokyo, Japan",
  "Kyoto, Japan",
  "Osaka, Japan",
  "Hiroshima, Japan",
  "Nara, Japan",
  "Seoul, South Korea",
  "Busan, South Korea",
  "Beijing, China",
  "Shanghai, China",
  "Hong Kong, China",
  "Macau, China",
  "Taipei, Taiwan",
  "Bangkok, Thailand",
  "Phuket, Thailand",
  "Chiang Mai, Thailand",
  "Singapore, Singapore",
  "Kuala Lumpur, Malaysia",
  "Penang, Malaysia",
  "Bali, Indonesia",
  "Jakarta, Indonesia",
  "Manila, Philippines",
  "Cebu, Philippines",
  "Boracay, Philippines",
  "Hanoi, Vietnam",
  "Ho Chi Minh City, Vietnam",
  "Halong Bay, Vietnam",
  "Siem Reap, Cambodia",
  "Phnom Penh, Cambodia",
  "Vientiane, Laos",
  "Yangon, Myanmar",
  "Colombo, Sri Lanka",
  "Galle, Sri Lanka",
  "Kathmandu, Nepal",
  "New Delhi, India",
  "Mumbai, India",
  "Bangalore, India",
  "Jaipur, India",
  "Agra, India",
  "Varanasi, India",
  "Goa, India",
  "Kerala, India",
  "Dubai, UAE",
  "Abu Dhabi, UAE",
  "Doha, Qatar",
  "Muscat, Oman",
  "Amman, Jordan",
  "Petra, Jordan",
  "Jerusalem, Israel",
  "Tel Aviv, Israel",
  "Istanbul, Turkey",
  "Ankara, Turkey",
  "Antalya, Turkey",
  "Tbilisi, Georgia",
  "Yerevan, Armenia",
  "Baku, Azerbaijan",

  // North America
  "New York City, USA",
  "Los Angeles, USA",
  "San Francisco, USA",
  "Las Vegas, USA",
  "Chicago, USA",
  "Miami, USA",
  "Orlando, USA",
  "Boston, USA",
  "Washington DC, USA",
  "Seattle, USA",
  "Portland, USA",
  "Denver, USA",
  "Austin, USA",
  "Nashville, USA",
  "New Orleans, USA",
  "San Diego, USA",
  "Phoenix, USA",
  "Philadelphia, USA",
  "Honolulu, USA",
  "Anchorage, USA",
  "Toronto, Canada",
  "Vancouver, Canada",
  "Montreal, Canada",
  "Quebec City, Canada",
  "Calgary, Canada",
  "Ottawa, Canada",
  "Mexico City, Mexico",
  "Cancun, Mexico",
  "Playa del Carmen, Mexico",
  "Tulum, Mexico",
  "Guadalajara, Mexico",
  "Monterrey, Mexico",
  "Puerto Vallarta, Mexico",
  "Cabo San Lucas, Mexico",

  // South America
  "Rio de Janeiro, Brazil",
  "São Paulo, Brazil",
  "Salvador, Brazil",
  "Brasilia, Brazil",
  "Buenos Aires, Argentina",
  "Mendoza, Argentina",
  "Ushuaia, Argentina",
  "Santiago, Chile",
  "Valparaiso, Chile",
  "Lima, Peru",
  "Cusco, Peru",
  "Machu Picchu, Peru",
  "Arequipa, Peru",
  "Bogota, Colombia",
  "Cartagena, Colombia",
  "Medellin, Colombia",
  "Quito, Ecuador",
  "Galapagos Islands, Ecuador",
  "La Paz, Bolivia",
  "Montevideo, Uruguay",
  "Asuncion, Paraguay",
  "Caracas, Venezuela",

  // Africa
  "Cairo, Egypt",
  "Luxor, Egypt",
  "Marrakech, Morocco",
  "Casablanca, Morocco",
  "Fez, Morocco",
  "Tunis, Tunisia",
  "Cape Town, South Africa",
  "Johannesburg, South Africa",
  "Durban, South Africa",
  "Nairobi, Kenya",
  "Mombasa, Kenya",
  "Dar es Salaam, Tanzania",
  "Zanzibar, Tanzania",
  "Kampala, Uganda",
  "Kigali, Rwanda",
  "Addis Ababa, Ethiopia",
  "Lagos, Nigeria",
  "Accra, Ghana",
  "Dakar, Senegal",

  // Oceania
  "Sydney, Australia",
  "Melbourne, Australia",
  "Brisbane, Australia",
  "Perth, Australia",
  "Adelaide, Australia",
  "Gold Coast, Australia",
  "Cairns, Australia",
  "Auckland, New Zealand",
  "Wellington, New Zealand",
  "Christchurch, New Zealand",
  "Queenstown, New Zealand",
  "Nadi, Fiji",
  "Suva, Fiji",
  "Papeete, French Polynesia",
  "Bora Bora, French Polynesia",
  "Apia, Samoa",
  "Nuku'alofa, Tonga",
  "Port Vila, Vanuatu",
  "Nouméa, New Caledonia",
  "Tumon, Guam",

  // Caribbean
  "Nassau, Bahamas",
  "Montego Bay, Jamaica",
  "Kingston, Jamaica",
  "Havana, Cuba",
  "San Juan, Puerto Rico",
  "Santo Domingo, Dominican Republic",
  "Punta Cana, Dominican Republic",
  "Bridgetown, Barbados",
  "Port of Spain, Trinidad and Tobago",
  "Willemstad, Curacao",
  "Oranjestad, Aruba",
  "Castries, St. Lucia",
  "St. John's, Antigua and Barbuda",
  "Philipsburg, St. Maarten",
  "Providenciales, Turks and Caicos",
  "George Town, Cayman Islands",

  // Central America
  "Panama City, Panama",
  "San Jose, Costa Rica",
  "Manuel Antonio, Costa Rica",
  "Guatemala City, Guatemala",
  "Antigua, Guatemala",
  "Belize City, Belize",
  "San Salvador, El Salvador",
  "Tegucigalpa, Honduras",
  "Managua, Nicaragua",
  "Granada, Nicaragua",
].sort()

/**
 * Search destinations by query
 */
export function searchDestinations(query: string, limit: number = 10): string[] {
  if (!query.trim()) return destinations.slice(0, limit)

  const lowerQuery = query.toLowerCase()
  const matches = destinations.filter(dest =>
    dest.toLowerCase().includes(lowerQuery)
  )

  // Prioritize matches that start with the query
  const startsWithQuery = matches.filter(dest =>
    dest.toLowerCase().startsWith(lowerQuery)
  )
  const otherMatches = matches.filter(dest =>
    !dest.toLowerCase().startsWith(lowerQuery)
  )

  return [...startsWithQuery, ...otherMatches].slice(0, limit)
}
