import type { ExcursionData } from '@/lib/types/viator'

/**
 * Generate mock excursion data for testing when API is unavailable
 */
export function getMockExcursions(destination: string, days: number = 5): ExcursionData[] {
  const mockData: ExcursionData[] = [
    {
      id: 'viator-1',
      title: `${destination} Highlights Walking Tour`,
      description: `Discover the best of ${destination} on this comprehensive walking tour with an expert local guide. Visit iconic landmarks and hidden gems.`,
      price: 45,
      rating: 4.8,
      reviewCount: 1250,
      duration: '3 hours',
      provider: 'Viator',
      thumbnail: '/placeholder.svg',
      category: 'Sightseeing',
      location: destination,
      affiliateLink: 'https://www.viator.com/tours/sample?affiliate_id=YOUR_ID',
    },
    {
      id: 'viator-2',
      title: `${destination} Food & Wine Tasting Experience`,
      description: `Savor the flavors of ${destination} with a guided food and wine tasting tour through local markets and restaurants.`,
      price: 89,
      rating: 4.9,
      reviewCount: 892,
      duration: '4 hours',
      provider: 'Viator',
      thumbnail: '/placeholder.svg',
      category: 'Food & Drink',
      location: destination,
      affiliateLink: 'https://www.viator.com/tours/sample?affiliate_id=YOUR_ID',
    },
    {
      id: 'viator-3',
      title: `${destination} Museum Skip-the-Line Ticket`,
      description: `Bypass the crowds with priority access to ${destination}'s most famous museum. Includes guided tour option.`,
      price: 65,
      rating: 4.7,
      reviewCount: 2100,
      duration: '2 hours',
      provider: 'Viator',
      thumbnail: '/placeholder.svg',
      category: 'Culture',
      location: destination,
      affiliateLink: 'https://www.viator.com/tours/sample?affiliate_id=YOUR_ID',
    },
    {
      id: 'gyg-1',
      title: `${destination} River Cruise with Dinner`,
      description: `Enjoy a romantic evening cruise with gourmet dining and stunning city views from the water.`,
      price: 125,
      rating: 4.8,
      reviewCount: 756,
      duration: '3 hours',
      provider: 'GetYourGuide',
      thumbnail: '/placeholder.svg',
      category: 'Food & Drink',
      location: destination,
      affiliateLink: 'https://www.getyourguide.com/sample?affiliate_id=YOUR_ID',
    },
    {
      id: 'viator-4',
      title: `${destination} Adventure Tour: Hiking & Nature`,
      description: `Explore the natural beauty around ${destination} with a guided hiking adventure. All equipment included.`,
      price: 78,
      rating: 4.9,
      reviewCount: 423,
      duration: '5 hours',
      provider: 'Viator',
      thumbnail: '/placeholder.svg',
      category: 'Adventure',
      location: destination,
      affiliateLink: 'https://www.viator.com/tours/sample?affiliate_id=YOUR_ID',
    },
    {
      id: 'gyg-2',
      title: `${destination} Bike Tour`,
      description: `See ${destination} from a different perspective on this guided bike tour through historic neighborhoods.`,
      price: 55,
      rating: 4.6,
      reviewCount: 1089,
      duration: '3 hours',
      provider: 'GetYourGuide',
      thumbnail: '/placeholder.svg',
      category: 'Adventure',
      location: destination,
      affiliateLink: 'https://www.getyourguide.com/sample?affiliate_id=YOUR_ID',
    },
    {
      id: 'viator-5',
      title: `${destination} Cooking Class Experience`,
      description: `Learn to cook authentic local cuisine with a professional chef. Includes market visit and meal.`,
      price: 95,
      rating: 5.0,
      reviewCount: 287,
      duration: '4 hours',
      provider: 'Viator',
      thumbnail: '/placeholder.svg',
      category: 'Food & Drink',
      location: destination,
      affiliateLink: 'https://www.viator.com/tours/sample?affiliate_id=YOUR_ID',
    },
    {
      id: 'viator-6',
      title: `${destination} Sunset Photography Tour`,
      description: `Capture stunning photos of ${destination} at golden hour with tips from a professional photographer.`,
      price: 72,
      rating: 4.8,
      reviewCount: 445,
      duration: '2.5 hours',
      provider: 'Viator',
      thumbnail: '/placeholder.svg',
      category: 'Sightseeing',
      location: destination,
      affiliateLink: 'https://www.viator.com/tours/sample?affiliate_id=YOUR_ID',
    },
  ]

  // Distribute activities across days
  return mockData.map((item, index) => ({
    ...item,
    id: `${item.id}-${index}`,
  }))
}
